### PR TITLE
Update the header compatible for  react native version v0.40

### PR DESCRIPTION
**Pull request by Amerr**
import Headers changed to work in react native v 0.40

### CODE REVIEW

**Comment by wootwoot1234** [comment]
Thanks!

**Comment by Amerr** [comment]
👍

**Comment by hellogerard** [comment]
@wootwoot1234 Can you publish the latest master to npm? Hate working off a git commit.

**Comment by wootwoot1234** [comment]
I thought I had.  Sorry about that.  Just updated it as version 1.1.0 on npm.

**Comment by wootwoot1234** [comment]
@hellogerard, have you tried using `ImageStore.getBase64ForTag(uri, success, failure)`?  I just saw that it might replace this library since it's [included in RN](https://facebook.github.io/react-native/docs/imagestore.html).

**Comment by hellogerard** [comment]
@wootwoot1234 Yes, actually. `ImageStore` does work for Android (and is what I used), but is broken (at least last I tried it) on iOS. So I this package gets it working for iOS.

**Comment by wootwoot1234** [comment]
Ok, cool.  Let me know if you ever stop using this library in favor of `ImageStore` so I can let other users know via the readme.

**Pull request merged**
